### ISSUE TITLE
panic: runtime error: slice bounds out of range [:-1]

### ISSUE THREAD

**Issue by dellgreen** [ui-kreinhard/go-cups-control-files#2]
```
github.com/ui-kreinhard/go-cups-control-files/controlFile.extractString(0x40d, 0xc000106000, 0x415, 0x615, 0xe)
	/home/dell/Programming/projects/upstream/go-cups-control-files/controlFile/parse.go:106 +0x10a
github.com/ui-kreinhard/go-cups-control-files/controlFile.strategy(0x3fd, 0xc000106000, 0x415, 0x615, 0xc00010a000)
	/home/dell/Programming/projects/upstream/go-cups-control-files/controlFile/parse.go:122 +0x1cd0
github.com/ui-kreinhard/go-cups-control-files/controlFile.ParseBytes(0xc000106000, 0x415, 0x615, 0x415)
	/home/dell/Programming/projects/upstream/go-cups-control-files/controlFile/parse.go:198 +0x67
main.main()
	/home/dell/Programming/projects/upstream/go-cups-control-files/main.go:21 +0x10f
```

Control file attached

[c00555.gz](https://github.com/ui-kreinhard/go-cups-control-files/files/6267633/c00555.gz)

**Comment by ui-kreinhard** [comment]
Thanks! Be aware this is a weekend project - I'll try to have a look at the upcoming weekend. I don't think it's a big deal. Thank you also for attaching the control file.

**Comment by dellgreen** [comment]
No problem, no rush, just thought you would like to know :)

**Comment by ui-kreinhard** [comment]
<pre><b>{</b>
<b>  </b><font color="#729FCF"><b>&quot;OperationsAttributesTag&quot;</b></font><b>: {</b>
<b>    </b><font color="#729FCF"><b>&quot;AttributesCharset&quot;</b></font><b>: </b><font color="#4E9A06">&quot;utf-8&quot;</font><b>,</b>
<b>    </b><font color="#729FCF"><b>&quot;AttributesNaturalLanguage&quot;</b></font><b>: </b><font color="#4E9A06">&quot;\u0005en-gb\u0002&quot;</font>
<b>  },</b>
<b>  </b><font color="#729FCF"><b>&quot;JobAttributesTag&quot;</b></font><b>: {</b>
<b>    </b><font color="#729FCF"><b>&quot;PrinterUri&quot;</b></font><b>: </b><font color="#4E9A06">&quot;ipp://localhost:631/printers/TTP-345&quot;</font><b>,</b>
<b>    </b><font color="#729FCF"><b>&quot;JobOriginatingUserName&quot;</b></font><b>: </b><font color="#4E9A06">&quot;dell&quot;</font><b>,</b>
<b>    </b><font color="#729FCF"><b>&quot;JobName&quot;</b></font><b>: </b><font color="#4E9A06">&quot;TTP-345 - CUPS 2.3.1&quot;</font><b>,</b>
<b>    </b><font color="#729FCF"><b>&quot;Copies&quot;</b></font><b>: </b>6<b>,</b>
<b>    </b><font color="#729FCF"><b>&quot;DocumentFormat&quot;</b></font><b>: </b><font color="#4E9A06">&quot;application/pdf&quot;</font><b>,</b>
<b>    </b><font color="#729FCF"><b>&quot;JobPriority&quot;</b></font><b>: </b>50<b>,</b>
<b>    </b><font color="#729FCF"><b>&quot;JobUuid&quot;</b></font><b>: </b><font color="#4E9A06">&quot;urn:uuid:6c852e96-5d13-3e75-4089-a365b416bcae&quot;</font><b>,</b>
<b>    </b><font color="#729FCF"><b>&quot;JobOriginatingHostName&quot;</b></font><b>: </b><font color="#4E9A06">&quot;localhost&quot;</font><b>,</b>
<b>    </b><font color="#729FCF"><b>&quot;TimeAtCreation&quot;</b></font><b>: </b>1617740601<b>,</b>
<b>    </b><font color="#729FCF"><b>&quot;TimeAtProcessing&quot;</b></font><b>: </b>553649770<b>,</b>
<b>    </b><font color="#729FCF"><b>&quot;TimeAtCompleted&quot;</b></font><b>: </b>553652340<b>,</b>
<b>    </b><font color="#729FCF"><b>&quot;JobId&quot;</b></font><b>: </b>555<b>,</b>
<b>    </b><font color="#729FCF"><b>&quot;JobState&quot;</b></font><b>: </b><font color="#4E9A06">&quot;pending&quot;</font><b>,</b>
<b>    </b><font color="#729FCF"><b>&quot;JobStateReasons&quot;</b></font><b>: </b><font color="#555753"><b>null</b></font><b>,</b>
<b>    </b><font color="#729FCF"><b>&quot;JobMediaSheetsCompleted&quot;</b></font><b>: </b>1869443180<b>,</b>
<b>    </b><font color="#729FCF"><b>&quot;JobPrinterUri&quot;</b></font><b>: </b><font color="#4E9A06">&quot;ipp://dells-Apollo/printers/TTP-345&quot;</font><b>,</b>
<b>    </b><font color="#729FCF"><b>&quot;JobKOctets&quot;</b></font><b>: </b>67<b>,</b>
<b>    </b><font color="#729FCF"><b>&quot;JobHoldUntil&quot;</b></font><b>: </b><font color="#4E9A06">&quot;no-hold&quot;</font><b>,</b>
<b>    </b><font color="#729FCF"><b>&quot;JobSheets&quot;</b></font><b>: </b><font color="#4E9A06">&quot;none,none&quot;</font><b>,</b>
<b>    </b><font color="#729FCF"><b>&quot;JobPrinterStateMessage&quot;</b></font><b>: </b><font color="#555753"><b>null</b></font><b>,</b>
<b>    </b><font color="#729FCF"><b>&quot;JobPrinterStateReasons&quot;</b></font><b>: </b><font color="#4E9A06">&quot;none&quot;</font>
<b>  }</b>
<b>}</b>
</pre>

Does this look familiar and corespond to your print job? :)

**Comment by ui-kreinhard** [comment]
Found it - returning -1 for end position is not a good idea :)

**Comment by dellgreen** [comment]
Looks good to me, it all now works, many thanks
